# Travis CI build file.

# whitelist (branches that should be built)
branches:
  only:
    - master
    - /^issue.*$/

# the matrix of builds should cover each combination of Swift version
# and platform that is supported. The version of Swift used is specified
# by .swift-version, unless SWIFT_SNAPSHOT is specified.
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      services: docker
      env: DOCKER_IMAGE=swift:5.0.3-xenial SWIFT_SNAPSHOT=5.0.3 DOCKER_PRIVILEGED=true SWIFT_TEST_ARGS="--parallel"
    - os: linux
      dist: xenial
      sudo: required
      services: docker
      env: DOCKER_IMAGE=swift:5.1 DOCKER_PRIVILEGED=true SWIFT_TEST_ARGS="--parallel --sanitize=thread" CUSTOM_TEST_SCRIPT=.kitura-test.sh
    - os: linux
      dist: xenial
      sudo: required
      services: docker
      env: DOCKER_IMAGE=swift:5.1 SWIFT_SNAPSHOT=$SWIFT_DEVELOPMENT_SNAPSHOT DOCKER_PRIVILEGED=true SWIFT_TEST_ARGS="--parallel --sanitize=thread"
    - os: osx
      osx_image: xcode10.2
      sudo: required
      env: SWIFT_SNAPSHOT=5.0.1 JAZZY_ELIGIBLE=true SWIFT_TEST_ARGS="--parallel"
    - os: osx
      osx_image: xcode11
      sudo: required
      env: SWIFT_TEST_ARGS="--parallel --sanitize=thread"
    - os: osx
      osx_image: xcode11
      sudo: required
      env: SWIFT_SNAPSHOT=$SWIFT_DEVELOPMENT_SNAPSHOT SWIFT_TEST_ARGS="--parallel --sanitize=thread" CUSTOM_TEST_SCRIPT=.kitura-test.sh


before_install:
  - git clone https://github.com/KituraKommunity/Package-Builder.git

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
